# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"

services:
  panda-postgresql:
    image: bitnami/postgresql:11.11.0
    ports:
      - "5432:5432"
    profiles: ["all", "schema"]
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: panda
    volumes:
      - panda-postgresql:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/5432"]
      interval: 5s
      timeout: 60s
      retries: 120
    networks:
      - panda

  panda-zookeeper:
    image: bitnami/zookeeper:3.6.2
    profiles: ["all"]
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
    volumes:
      - panda-zookeeper:/bitnami/zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/2181"]
      interval: 5s
      timeout: 60s
      retries: 120
    networks:
      - panda

  panda-schema-initializer:
    image: ${HUB}/panda-tools:${TAG}
    env_file: .env
    profiles: ["schema"]
    command: [ tools/bin/upgrade-schema.sh ]
    depends_on:
      panda-postgresql:
        condition: service_healthy
    volumes:
      - panda-logs:/opt/panda/logs
      - panda-shared-local:/opt/soft
      - panda-resource-local:/panda
    networks:
      - panda

  panda-api:
    image: ${HUB}/panda-api:${TAG}
    ports:
      - "12345:12345"
      - "25333:25333"
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:12345/panda/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      panda-zookeeper:
        condition: service_healthy
    volumes:
      - panda-logs:/opt/panda/logs
      - panda-shared-local:/opt/soft
      - panda-resource-local:/panda
    networks:
      - panda

  panda-worker:
    image: ${HUB}/panda-worker:${TAG}
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:1235/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      panda-zookeeper:
        condition: service_healthy
    volumes:
      - panda-worker-data:/tmp/panda
      - panda-logs:/opt/panda/logs
      - panda-shared-local:/opt/soft
      - panda-resource-local:/panda
    networks:
      - panda

networks:
  panda:
    driver: bridge

volumes:
  panda-postgresql:
  panda-zookeeper:
  panda-worker-data:
  panda-logs:
  panda-shared-local:
  panda-resource-local:
